Repository TrainerKarthi/practicewithfriends, pull requests merged in 2025-02, with the labels that each got.

#2 #AB:Home Page created
  home.html
Labels: New Task

#3 #AB:Likith created project
  gitpractice/app/__init__.py
  gitpractice/app/admin.py
  gitpractice/app/apps.py
  gitpractice/app/migrations/__init__.py
  gitpractice/app/models.py
  gitpractice/app/tests.py
  gitpractice/app/views.py
  gitpractice/gitpractice/__init__.py
  gitpractice/gitpractice/__pycache__/__init__.cpython-313.pyc
  gitpractice/gitpractice/__pycache__/settings.cpython-313.pyc
  gitpractice/gitpractice/asgi.py
  gitpractice/gitpractice/settings.py
  gitpractice/gitpractice/urls.py
  gitpractice/gitpractice/wsgi.py
  gitpractice/manage.py
Labels: documentation

#4 Karthik task2 has been completed
  A.java
  myFile1.txt
Labels: bug

#5 #AB:navigation bar added
  home.html
Labels: New Task
